#! /usr/bin/env ruby

require 'optparse'
require 'date'
require './abstract_solution.rb'

def main(options)
  day = options[:day] || Date.today.day
  year = options[:year] || Date.today.year

  if options[:generate]
    `./scripts/get-problem.sh #{year} #{day} #{options[:typescript] ? 'typescript' : ''}`
  elsif options[:typescript]
    directory = "#{year}/day#{day}"
    system("yarn ts-node #{directory}/problem.ts")
  else
    directory = "#{year}/day#{day}"
    require "./#{year}/day#{day}/problem.rb"
    f = File.open("#{directory}/input.txt")
    Solution.new.solve(f.read, skip_test_cases: options[:skip], year: year, day: day)
  end
end

options = {}
OptionParser.new do |opts|
  opts.banner = 'Usage: solve.rb 12'
  opts.on('-dDAY', '--day DAY', 'Day (Defaults to Current Day)') { |d| options[:day] = d }
  opts.on('-yYEAR', '--year YEAR', 'Year (Defaults to Current Year)') { |y| options[:year] = y }
  opts.on('-g', '--get-problem', 'Download Problem and Set Up Directory') { options[:generate] = true }
  opts.on('-s', '--skip', 'Skip Test Cases') { options[:skip] = true }
  opts.on('-t', '--typescript', 'Solve solution in typescript') { options[:typescript] = true }
end.parse!

main(options)
